---
# Do not run this role every time
- name: Find recent run marker
  find:
    paths: /tmp
    pattern: '{{ role_name }}.{{ common.cache_key }}.run-marker'
    age: -1h
  register: run_marker

- become: yes
  when: run_marker.files | length == 0 or not common.enable_cache
  block:

  - name: Apt update
    apt:
      update_cache: yes
      cache_valid_time: 36000
    # For Russia
    retries: 3
    delay: 10  

  - name: Install tools
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - apt-transport-https 
    - ca-certificates    
    - net-tools
    - nmap
    - htop
    - iotop
    - git-crypt
    - neovim
    - python3-pip
    - traceroute
    # Installing via PIP does not always work
    - python-pexpect

  - name: Install commonly used python packages
    pip:
      name: "{{ item }}"
      umask: "0022"
    loop: 
    - pexpect
    - passlib
    - dnspython

  - name: Get /etc/apt/apt.conf.d/20auto-upgrades stat
    stat:
      path: /etc/apt/apt.conf.d/20auto-upgrades
    register: config

  - name: Disable automatic updates for APT
    lineinfile:
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      state: present
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    when: config.stat.exists
    loop:
    - regexp: "^APT::Periodic::Update-Package-Lists"
      line: APT::Periodic::Update-Package-Lists "0";
    - regexp: "^APT::Periodic::Download-Upgradeable-Packages"
      line: APT::Periodic::Download-Upgradeable-Packages "0";
    - regexp: "^APT::Periodic::AutocleanInterval"
      line: APT::Periodic::AutocleanInterval "0";
    - regexp: "^APT::Periodic::Unattended-Upgrade"
      line: APT::Periodic::Unattended-Upgrade "1";

  # https://askubuntu.com/questions/930593/how-to-disable-autorefresh-in-snap#:~:text=Disable%20automatic%20updating%20if%20the,the%20connection%20as%20being%20metered.&text=refresh.,-metered%3Dhold%20only
  # Enable again:
  # sudo systemctl unmask snapd.service
  # sudo systemctl start  snapd.service
  # sudo snap refresh  

  # Will not work: https://github.com/ansible/ansible/issues/68536
  # Malformed output discovered from systemd list-unit-files: accounts-daemon.service
  # - name: Populate service facts
  #   service_facts:

  - name: Get services
    command: systemctl list-unit-files
    register: units
    changed_when: false

  # Ubuntu 20.04 instances do not have snapd installed on YandexCloud
  - when: "'snapd.service' in units.stdout"
    block: 

    - name: Stop snapd service
      service: 
        name: snapd.service 
        state: stopped

    - name: Mask snapd service
      command: systemctl mask snapd.service
      register: r
      changed_when: "'Created symlink' in r.stdout" 

  - name: Create run marker
    file:
      path: /tmp/{{ role_name }}.{{ common.cache_key }}.run-marker
      state: touch      

  - name: Change hostanme
    hostname:
      name: "{{ hostname }}"
      use: systemd
    when: hostname is defined

